CV/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('article/', include('articles.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/urls.py
from django.urls import path
from .views import detail

app_name = 'articles'

urlpatterns = [
    path('detail/<slug:slug>/', detail, name='detail', )
]

main/urls.py
from django.urls import path

from main.views import index

app_name = 'main'

urlpatterns = [
    path('', index, name='index')
]

articles/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.dispatch import receiver


class Author(models.Model):
    name = models.CharField(max_length=255)
    bio = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='media/articles/', null=True, blank=True)


class Category(models.Model):
    title = models.CharField(max_length=255)


class Tag(models.Model):
    title = models.CharField(max_length=255)


class Article(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='media/articles/', blank=True, null=True)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, blank=True)
    tags = models.ManyToManyField(Tag)
    categories = models.ManyToManyField(Category)

    class Meta:
        verbose_name = "Articles"


class SubArticle(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, null=True, blank=True)
    content = models.TextField(null=True, blank=True)


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', models.SET_NULL, null=True)
    top_level_comment_id = models.IntegerField(null=True, blank=True)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    image = models.ImageField(upload_to='media/articles', null=True, blank=True)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    @property
    def children(self):
        if not self.parent:
            return Comment.objects.filter(top_level_comment_id=self.id)
        return None


@receiver(pre_save, sender=Comment)
def pre_save_comments(sender, instance, *args, **kwargs):
    if instance.parent:
        if instance.parent.top_level_comment_id:
            instance.top_level_comment_id = instance.parent.top_level_comment_id
        else:
            instance.top_level_comment_id = instance.parent.id


@receiver(pre_save, sender=Article)
def pre_save_article(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.title + '-' + str(timezone.now()))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from preview.colorlib.com/theme/ronaldo/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 27 Jan 2024 13:54:06 GMT -->
<head>
    <title>Ronaldo - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script nonce="322073c6-50be-43eb-b5d0-e79ddb98cc88">try {
        (function (w, d) {
            !function (b$, ca, cb, cc) {
                b$[cb] = b$[cb] || {};
                b$[cb].executed = [];
                b$.zaraz = {deferred: [], listeners: []};
                b$.zaraz.q = [];
                b$.zaraz._f = function (cd) {
                    return async function () {
                        var ce = Array.prototype.slice.call(arguments);
                        b$.zaraz.q.push({m: cd, a: ce})
                    }
                };
                for (const cf of ["track", "set", "debug"]) b$.zaraz[cf] = b$.zaraz._f(cf);
                b$.zaraz.init = () => {
                    var cg = ca.getElementsByTagName(cc)[0], ch = ca.createElement(cc),
                        ci = ca.getElementsByTagName("title")[0];
                    ci && (b$[cb].t = ca.getElementsByTagName("title")[0].text);
                    b$[cb].x = Math.random();
                    b$[cb].w = b$.screen.width;
                    b$[cb].h = b$.screen.height;
                    b$[cb].j = b$.innerHeight;
                    b$[cb].e = b$.innerWidth;
                    b$[cb].l = b$.location.href;
                    b$[cb].r = ca.referrer;
                    b$[cb].k = b$.screen.colorDepth;
                    b$[cb].n = ca.characterSet;
                    b$[cb].o = (new Date).getTimezoneOffset();
                    if (b$.dataLayer) for (const cm of Object.entries(Object.entries(dataLayer).reduce(((cn, co) => ({...cn[1], ...co[1]})), {}))) zaraz.set(cm[0], cm[1], {scope: "page"});
                    b$[cb].q = [];
                    for (; b$.zaraz.q.length;) {
                        const cp = b$.zaraz.q.shift();
                        b$[cb].q.push(cp)
                    }
                    ch.defer = !0;
                    for (const cq of [localStorage, sessionStorage]) Object.keys(cq || {}).filter((cs => cs.startsWith("_zaraz_"))).forEach((cr => {
                        try {
                            b$[cb]["z_" + cr.slice(7)] = JSON.parse(cq.getItem(cr))
                        } catch {
                            b$[cb]["z_" + cr.slice(7)] = cq.getItem(cr)
                        }
                    }));
                    ch.referrerPolicy = "origin";
                    ch.src = "https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z=" + btoa(encodeURIComponent(JSON.stringify(b$[cb])));
                    cg.parentNode.insertBefore(ch, cg)
                };
                ["complete", "interactive"].includes(ca.readyState) ? zaraz.init() : b$.addEventListener("DOMContentLoaded", zaraz.init)
            }(w, d, "zarazData", "script");
        })(window, document)
    } catch (err) {
        console.error('Failed to run Cloudflare Zaraz: ', err)
        fetch('/cdn-cgi/zaraz/t', {
            credentials: 'include',
            keepalive: true,
            method: 'GET',
        })
    }
    ;</script>
</head>
<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

{% include 'navbar.html' %}

{% block content %}

{% endblock %}

{% include 'footer.html' %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317"
        integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA=="
        data-cf-beacon='{"rayId":"84c17c543ab21fb6","version":"2024.1.0","token":"cd0b4b3a733644fc843ef0b185f98241"}'
        crossorigin="anonymous"></script>
</body>

<!-- Mirrored from preview.colorlib.com/theme/ronaldo/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 27 Jan 2024 13:54:47 GMT -->
</html>

templates/blog.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
<script nonce="b9227435-b47f-439a-9f84-10a04494bdbe">try { (function(w,d){!function(b$,ca,cb,cc){b$[cb]=b$[cb]||{};b$[cb].executed=[];b$.zaraz={deferred:[],listeners:[]};b$.zaraz.q=[];b$.zaraz._f=function(cd){return async function(){var ce=Array.prototype.slice.call(arguments);b$.zaraz.q.push({m:cd,a:ce})}};for(const cf of["track","set","debug"])b$.zaraz[cf]=b$.zaraz._f(cf);b$.zaraz.init=()=>{var cg=ca.getElementsByTagName(cc)[0],ch=ca.createElement(cc),ci=ca.getElementsByTagName("title")[0];ci&&(b$[cb].t=ca.getElementsByTagName("title")[0].text);b$[cb].x=Math.random();b$[cb].w=b$.screen.width;b$[cb].h=b$.screen.height;b$[cb].j=b$.innerHeight;b$[cb].e=b$.innerWidth;b$[cb].l=b$.location.href;b$[cb].r=ca.referrer;b$[cb].k=b$.screen.colorDepth;b$[cb].n=ca.characterSet;b$[cb].o=(new Date).getTimezoneOffset();if(b$.dataLayer)for(const cm of Object.entries(Object.entries(dataLayer).reduce(((cn,co)=>({...cn[1],...co[1]})),{})))zaraz.set(cm[0],cm[1],{scope:"page"});b$[cb].q=[];for(;b$.zaraz.q.length;){const cp=b$.zaraz.q.shift();b$[cb].q.push(cp)}ch.defer=!0;for(const cq of[localStorage,sessionStorage])Object.keys(cq||{}).filter((cs=>cs.startsWith("_zaraz_"))).forEach((cr=>{try{b$[cb]["z_"+cr.slice(7)]=JSON.parse(cq.getItem(cr))}catch{b$[cb]["z_"+cr.slice(7)]=cq.getItem(cr)}}));ch.referrerPolicy="origin";ch.src="/cdn-cgi/zaraz/s.js?z="+btoa(encodeURIComponent(JSON.stringify(b$[cb])));cg.parentNode.insertBefore(ch,cg)};["complete","interactive"].includes(ca.readyState)?zaraz.init():b$.addEventListener("DOMContentLoaded",zaraz.init)}(w,d,"zarazData","script");})(window,document) } catch (err) {
      console.error('Failed to run Cloudflare Zaraz: ', err)
      fetch('/cdn-cgi/zaraz/t', {
        credentials: 'include',
        keepalive: true,
        method: 'GET',
      })
    };</script></head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.41 (Ubuntu) Server at preview.colorlib.com Port 443</address>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317" integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA==" data-cf-beacon='{"rayId":"84c17dd8adfe099b","b":1,"version":"2024.1.0","token":"cd0b4b3a733644fc843ef0b185f98241"}' crossorigin="anonymous"></script>
</body></html>

templates/footer.html
<footer class="ftco-footer ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">About</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia,
                        there
                        live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-4">
                    <h2 class="ftco-heading-2">Links</h2>
                    <ul class="list-unstyled">
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Home</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>About</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Services</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Projects</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Contact</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Services</h2>
                    <ul class="list-unstyled">
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Design</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Development</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Business Strategy</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Data Analysis</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Graphic Design</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text"><span
                                    class="__cf_email__" data-cfemail="254c4b434a655c4a5057414a48444c4b0b464a48">[email&#160;protected]</span></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <p>
                    Copyright &copy;<script data-cfasync="false"
                                            src="https://preview.colorlib.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger"
                                                                        aria-hidden="true"></i> by <a
                        href="https://colorlib.com/" target="_blank">Colorlib</a>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar ftco-navbar-light site-navbar-target" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'main:index' %}"><span>S</span>herzod</a>
        <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse"
                data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav nav ml-auto">
                <li class="nav-item"><a href="{% url 'main:index' %}#home-section" class="nav-link"><span>Home</span></a></li>
                <li class="nav-item"><a href="{% url 'main:index' %}#about-section" class="nav-link"><span>About</span></a></li>
                <li class="nav-item"><a href="{% url 'main:index' %}#resume-section" class="nav-link"><span>Resume</span></a></li>
                <li class="nav-item"><a href="{% url 'main:index' %}#services-section" class="nav-link"><span>Services</span></a></li>
                <li class="nav-item"><a href="{% url 'main:index' %}#projects-section" class="nav-link"><span>Projects</span></a></li>
                <li class="nav-item"><a href="{% url 'main:index' %}#blog-section" class="nav-link"><span>My Blog</span></a></li>
                <li class="nav-item"><a href="{% url 'main:index' %}#contact-section" class="nav-link"><span>Contact</span></a></li>
            </ul>
        </div>
    </div>
</nav>

templates/single.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
    <div class="hero-wrap js-fullheight">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight justify-content-center align-items-center">
                <div class="col-lg-10 ftco-animate d-flex align-items-center">
                    <div class="text text-center">
                        <h1 class="mb-3 bread">Blog Single Post</h1>
                        <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'main:index' %}">Home <i
                                class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a
                                href="{% url 'main:index' %}">Blog <i
                                class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single <i
                                class="ion-ios-arrow-forward"></i></span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="ftco-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 ftco-animate">
                    <h2 class="mb-3">{{ article.title }}</h2>
                    <p>{{ article.content }}</p>
                    <p style="max-width: 80%; text-align: center; margin: 0 auto">
                        <img src="{{ article.image.url }}" alt class="img-fluid">
                    </p>
                    {% if article.subarticle_set.all %}
                        {% for subarticle in article.subarticle_set.all %}
                            {% if subarticle.title %}
                                <h3>{{ subarticle.title }}</h3>
                            {% endif %}
                            <p>{{ subarticle.content }}</p>
                        {% endfor %}
                    {% endif %}

                    <div class="tag-widget post-tag-container mb-5 mt-5">
                        <div class="tagcloud">
                            <a href="#" class="tag-cloud-link">Life</a>
                            <a href="#" class="tag-cloud-link">Sport</a>
                            <a href="#" class="tag-cloud-link">Tech</a>
                            <a href="#" class="tag-cloud-link">Travel</a>
                        </div>
                    </div>
                    <div class="about-author d-flex p-4 bg-light">
                        <div class="bio mr-5">
                            <img src="{{ article.author.image.url }}" alt="Image placeholder"
                                 class="img-fluid mb-4">
                        </div>
                        <div class="desc">
                            <h3>{{ article.author.name }}</h3>
                            <p>{{ article.author.bio }}</p>
                        </div>
                    </div>


                    <div class="pt-5 mt-5">
                        <h3 class="mb-5">{{ comments.count }} Comments</h3>
                        {% for comment in comments %}
                            <ul class="comment-list">
                                <li class="comment">
                                    <div class="vcard bio">
                                        {% if comment.image %}
                                            <img src="{{ comment.image.url }}"
                                                 alt="Image placeholder">
                                        {% else %}
                                            <img src="{% static 'images/profile_default.png' %}"
                                                 alt="Image placeholder">
                                        {% endif %}
                                    </div>
                                    <div class="comment-body">
                                        <h3>{{ comment.name }}</h3>
                                        <div class="meta">{{ comment.created_at }}</div>
                                        <p>{{ comment.message }}</p>
                                        <p><a href="?cid={{ comment.id }}#comment-form-reply" class="reply">Reply</a>
                                        </p>
                                    </div>
                                </li>
                                {% if comment.children %}
                                    {% for child in comment.children %}
                                        <div style="margin-left: 50px">
                                            <li class="comment ml-md-4">
                                                <div class="vcard bio">
                                                    {% if comment.image %}
                                                        <img src="{{ comment.image.url }}"
                                                             alt="Image placeholder">
                                                    {% else %}
                                                        <img src="{% static 'images/profile_default.png' %}"
                                                             alt="Image placeholder">
                                                    {% endif %}
                                                </div>
                                                <div class="comment-body">
                                                    <code>{{ child.parent.name }} < {{ child.name }}</code>
                                                    <h3>{{ child.name }}</h3>
                                                    <div class="meta">{{ child.created_at }}</div>
                                                    <p>{{ child.message }}</p>
                                                    <p><a href="?cid={{ child.id }}#comment-form-reply" class="reply">Reply</a>
                                                    </p>
                                                </div>
                                            </li>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </ul>

                        {% endfor %}

                        <div class="comment-form-wrap pt-5" id="comment-form-reply">
                            <h3 class="mb-5">Leave a comment</h3>
                            <form method="post" class="p-5 bg-light" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="name">Name *</label>
                                    {{ form.name }}
                                </div>
                                <div class="form-group">
                                    <label for="image">Image *</label>
                                    {{ form.image }}
                                </div>
                                <div class="form-group">
                                    <label for="email">E-mail</label>
                                    {{ form.email }}
                                </div>
                                <div class="form-group">
                                    <label for="message">Message</label>
                                    {{ form.message }}
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                                </div>
                            </form>
                        </div>
                    </div>


                </div>
                <div class="col-lg-4 sidebar ftco-animate">
                    <div class="sidebar-box">
                        <form action="#" class="search-form">
                            <div class="form-group">
                                <span class="icon icon-search"></span>
                                <input name="q" type="text" class="form-control" placeholder="Search...">
                            </div>
                        </form>
                    </div>
                    <div class="sidebar-box ftco-animate">
                        <h3 class="heading-sidebar">Recent Blog</h3>
                        {% for article in articles %}
                            <div class="block-21 mb-4 d-flex">
                                <a class="blog-img mr-4" style="background-image: url({{ article.image.url }});"></a>
                                <div class="text">
                                    <h3 class="heading"><a
                                            href="{% url 'articles:detail' article.slug %}">{{ article.title|slice:'50' }}</a>
                                    </h3>
                                    <div class="meta">
                                        <div>
                                            <a href="#"><span class="icon-calendar"></span>{{ article.created_date }}
                                            </a>
                                        </div>
                                        <div><a href="#"><span class="icon-person"></span>{{ article.author }}</a></div>
                                        <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                    <div class="sidebar-box ftco-animate">
                        <h3 class="heading-sidebar">Categories</h3>
                        <ul class="categories">
                            {% for category in categories %}
                                <li><a href="#">{{ category.title }} <span>(12)</span></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="sidebar-box ftco-animate">
                        <h3 class="heading-sidebar">Tag Cloud</h3>
                        <div class="tagcloud">
                            {% for tag in tags %}
                                <a href="#" style="color: #16181b" class="tag-cloud-link">{{ tag.title }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
<!-- Mirrored from preview.colorlib.com/theme/ronaldo/single.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 27 Jan 2024 13:55:09 GMT -->